replicaCount: 1

image:
  repository: ghcr.io/jzacharie/keryx-orchestrator
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80

hostNetwork: true

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: keryx.p.zacharie.org
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 2Gi

env:
  RUST_LOG: "trace"
  REDIS_URL: "redis://dragonfly.dragonfly.svc.cluster.local:6379"
  S3_BUCKET: "keryx-raw"
  S3_REGION: "eu-west-1"
  S3_ENDPOINT: "http://minio:9000"
  AWS_ACCESS_KEY_ID: "keryx2"
  AWS_SECRET_ACCESS_KEY: "4DoK6ArcksSBZJIznybMEleQ9cWMsCOTf02IdLII"
  EXTRACTOR_URL: "http://keryx-extractor:8010"
  DEWATERMARK_URL: "http://keryx-dewatermark:8000"
  VOICE_EXTRACTOR_URL: "http://keryx-voice-extractor:8000"
  VIDEO_COMPOSER_URL: "http://keryx-video-composer:8000"
  VIDEO_GENERATOR_URL: "http://keryx-wan2gp:8014"
  VOICE_CLONER_URL: "http://keryx-voice-cloner:9880"

imagePullSecrets:
  - name: ghcr-login

nodeSelector:
  kubernetes.io/hostname: vm169

tolerations: []
affinity: {}
