apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keryx-ingestor-scaler
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["http.keda.sh"]
  resources: ["httpscaledobjects"]
  verbs: ["get", "list", "patch", "update"]
