replicaCount: 1

image:
  repository: ghcr.io/jzacharie/keryx-diffusion-engine
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  limits:
    memory: 12Gi
    cpu: 4000m
  requests:
    memory: 12Gi
    cpu: 4000m

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 1000

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

nodeSelector:
  kubernetes.io/hostname: vm169

tolerations:
  - key: "special-node"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"

env:
  S3_ENDPOINT: "https://minio-170-api.zacharie.org"
  S3_BUCKET: "keryx"
  MODEL_ID: "stabilityai/sdxl-turbo"
  AWS_ACCESS_KEY_ID: "REDACTED" # pragma: allowlist secret
  AWS_SECRET_ACCESS_KEY: "REDACTED" # pragma: allowlist secret
