apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diffusion-engine-cache-pvc
  namespace: keryx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: proxmox-aquabot-bpool-xfs-i
