apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keryx-orchestrator-scaler-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: keryx
roleRef:
  kind: ClusterRole
  name: keryx-orchestrator-scaler
  apiGroup: rbac.authorization.k8s.io
